### ISSUE TITLE
Proxies not working

### ISSUE THREAD

**Issue by ioncodes** [nborrmann/jodel_api#12]
If I use proxies, it doesn't work. I tried setting the kwargs directly and by filling all args until I can set it.
I set proxies={'http':'proxy:port'}. It doesn't even try to connect to my proxy, and I'm 100% sure that the proxy works.

**Comment by nborrmann** [comment]
Try setting a 'https' proxy.

Anyway, this is most certainly a problem with the `requests` library (read up on their docs), so I'm closing this.
