### ISSUE TITLE
Voting

### ISSUE THREAD

**Issue by smillingDeath** [nborrmann/jodel_api#2]
Hi,
is it possible that Up and Downvoting is currently not working? 
The API seems to be unable to locate the Post:
(200, {'post': None, 'vote_count': 0})
When I´m getting the details of the jodel specified everything seems to be working

**Comment by nborrmann** [comment]
Yep, I see this behaviour for new accounts. Voting is still working on all my old ones though. So maybe new accounts are only able to vote after a certain time. 

Btw:

> (200, {'post': None, 'vote_count': 0})

This is the usual answer, if you've already voted on a post, or if the post doesn't exist anymore.

**Comment by smillingDeath** [comment]
Good to know, thanks man ;)

Might be possible that they created a minimum amount of karma and/or a time limit.
One of my accounts created yesterday got about 2500 karma and is working pretty good.
