### ISSUE TITLE
477: signed request expected

### ISSUE THREAD

**Issue by kontez** [nborrmann/jodel_api#27]
## Issue
When running ` j = jodel_api.JodelAccount(lat=lat, lng=lng, city=city)` I get  an exception which says `Exception: (477, "signed request expected")`
As suggested in the README.md, I have the latest jodel_api available since I just cloned it
...

## Environment

If you're reporting a bug, please attach the output of the following commands:

```
$ pip show jodel_api => version is 1.1.5
$ pip -V => 9.0.1
$ python -V => 3.6.1
$ python -c "import jodel_api; print(jodel_api.JodelAccount.version); print(jodel_api.JodelAccount.secret)"
```

**Comment by nborrmann** [comment]
Fixed in  54e46ef.

**Comment by kontez** [comment]
thanks for that, how is the key updated?
So I can do it by myself when this one expires

**Comment by nborrmann** [comment]
I'm using this project. But it's pretty complicated to get running:

https://bitbucket.org/cfib90/ojoc-keyhack

**Comment by kontez** [comment]
okay thanks!

**Comment by Frenor** [comment]
Key updated again?
