### ISSUE TITLE
Json parser error

### ISSUE THREAD

**Issue by gaurav-stepin** [nborrmann/jodel_api#29]
Hello There,
I am trying to use get_post_details api but not sure what format it reutrns data with. I assumed it is json. But JSON parser returns error saying it is not a valid json. Here is the sample of output I am getting. 
(200, {u'distance': ###, u'post_own': u'friend', u'user_handle': u'oj', u'discovered_by': 0, u'color': u'FFBA00', u'created_at': u'######', u'notifications_enabled': False, u'updated_at': u'#####', u'children': [{u'distance': #####, u'post_own': u'friend', u'user_handle': u'replier', u'discovered_by': 0, u'color': u'FFBA00', u'created_at': u'######', u'updated_at': u'##########3', u'post_id': u'XXXXXXXXXXXXXXXXXX', u'vote_count': 0, u'location': {u'loc_coordinates': {u'lat': 0, u'lng': 0}, u'loc_accuracy': 0, u'city': u'', u'name': u'far', u'country': u''}, u'message': u'\u0627\u064a \u0648\u0627\u0644\u0644\u0647', u'thanks_count': 0}], u'post_id': u'########', u'vote_count': 10, u'got_thanks': False, u'child_count': 1, u'replier': 0, u'location': {u'loc_coordinates': {u'lat': 0, u'lng': 0}, u'loc_accuracy': 0, u'city': u'', u'name': u'####', u'country': u''}, u'message': u'\u064a\u0627 \u0632\u064a\u0646 \u0631\u0645\u0636\u0627\u0646', u'pin_count': 0, u'share_count': 1, u'thanks_count': 0}) 

Here if you notice "u'" are there which is strange. Also I tried sample output you have provided with documentation. 

(200, {'token_type': 'bearer', 'access_token': 'xxx', 'expires_in': 604800, 'expiration_date': xxx})

This also gives error in json parser. So I tried different formats and found that this may be a yml formal. I tried that and it worked so is this yml format? If yes then still the get post details result is not validated with even yaml. 

May be I have missed something. Can you please drive me forward? 
Many Thanks

**Comment by nborrmann** [comment]
All functions return a python ``dict`` that was parsed from the json response. You don't need to parse it anymore.

As for the ``u''`` strings, that's a unicode string (you're using python2 right?), you can convert it into a normal string by doing ``u'xxx'.encode("utf-8")``.

**Comment by gaurav-stepin** [comment]
Hello nborrmann,
Many thanks. Clear to me. And it has worked well now. 
Cheerz,
