### ISSUE TITLE
Connecting with existing mobilephone-account?

### ISSUE THREAD

**Issue by chpo7234** [nborrmann/jodel_api#30]
Is it somehow possible to get the values "access_token", "device_uid", "distinct_id", "expiration_date" and "refresh_token" from an existing mobilephone account? I want to control my mobilephone-account with this API but "burp suite" just gives me a longer value called "iid". Other values seems to be encoded.

I will add a screenshot of these "encoded" values later on.

Any tips?

Greetings.

**Comment by nborrmann** [comment]
When you're looking at any request in burp suite, there should be a header like ``Authorization: Bearer xxxxx-xxxx-xxxx-xxxx``. That value (the x's) is the ``access_token``. 

You can create a new account using jodel_api and then set ``j.access_token`` to that value. Then all requests (except ``refresh_access_token`` and ``refresh_all_tokens``) should be working using your phone's account. But that means, when the access_token expires (after 7 days), you need to pull the new one from burpsuite. 

To get entire control of the account you'd need the ``device_uid``. I don't immediately know an easy way to get that.

Maybe you can force Jodel to issue a refresh_token request by changing your phone's date to something 7 days in the future and you will get to see the device_uid in burpsuite. (Though I haven't tested this.)

**Comment by chpo7234** [comment]
Thank you very much, nborrmann!

**Comment by nborrmann** [comment]
I'm curious, did you try changing the date, or did you just extract the access_token?

Also, what do you mean by "iid" and the encoded values? Could you post a screenshot of those? Thanks.

**Comment by chpo7234** [comment]
I just extracted the access_token. I will add the screenshots in the evening.

**Comment by chpo7234** [comment]
Ok, i didnt find the value "iid" again.. Maybe it came from another app, sorry.. 
I found out that the encoded values comes from _analytics.ext.go-tellm.com_, not directly from _api.go-tellm.com_:
https://www2.pic-upload.de/img/33300378/Unbenannt.jpg

I think i can ignore the analytics-traffic.

Greetings
