### ISSUE TITLE
New Secret

### ISSUE THREAD

**Issue by smillingDeath** [nborrmann/jodel_api#4]
Hi,
it´s seems like they started to force the use of the 4.24.4 secret right now.
Would you mind updating it?
BTW: How do you obtain the secret? I tried to generate it from the App but failed...
Greetings

**Comment by nborrmann** [comment]
Thanks for the PR.

I originally obtained the secret myself by reverse engineering the android app. But recently I've only copied from [these guys](https://bitbucket.org/cfib90/ojoc).
