### ISSUE TITLE
text-only comments not in the children property

### ISSUE THREAD

**Issue by jeyemwey** [nborrmann/jodel_api#53]
## Issue

When parsing a post with `retVal, post = j.get_post_details(post_id)`, the resulting `post[u'children']` only contain those comments that have an image attached.

For example, the famous [Frankfurt Love Story-Jodel](https://share.jodel.com/post?postId=5a04bdeeaefa5300175231c9) only has seven items in its children property dispite having hundreds of comments that are not there.

When a post only has text-only comments, `post[u'children']` is empty.

## Environment

Windows Subsystem for Linux (WSL), with Ubuntu 16.04 installed.

```bash
jannik@Surface:~/dev/jodel_api$ pip show jodel_api
Name: jodel-api
Version: 1.2.7
Summary: Unoffical Python Interface to the Jodel API
Home-page: https://github.com/nborrmann/jodel_api
Author: Nils Borrmann
Author-email: n.borrmann@googlemail.com
License: MIT
Location: /home/jannik/.local/lib/python2.7/site-packages
Requires: requests, future, mock, protobuf, varint

jannik@Surface:~/dev/jodel_api$ pip -V
pip 9.0.1 from /home/jannik/.local/lib/python2.7/site-packages (python 2.7)

jannik@Surface:~/dev/jodel_api$ python -V
Python 2.7.12

jannik@Surface:~/dev/jodel_api$ python -c "import jodel_api; print(jodel_api.JodelAccount.version); print(jodel_api.JodelAccount.secret)"
4.71.0
rpcrPfxRSeJZOXCXffvtJzRtTXnVlZAorilbRYOa
```

**Comment by nborrmann** [comment]
Apparently the `get_post_details` endpoint has been deprecated. You need to use `get_post_details_v3()`.
