### ISSUE TITLE
Signing key changed.

### ISSUE THREAD

**Issue by ioncodes** [nborrmann/jodel_api#57]
The current version is 4.75.2 and your repo is not updated. Also my extraction tools are not able to get the new key and your jodeldecompile project isn't able to find them aswell. Did they introduce a new method?

**Comment by ioncodes** [comment]
Nevermind, was able to get it.

**Comment by nborrmann** [comment]
Mind sending a pull request? Thanks!

**Comment by vaahtokarkki** [comment]
The key seems to be changed again and I can't get the jodelcompile working, maybe because of lack of docs. My old account got inactive and refreshing tokens won't get it back working so it could create posts.

**Comment by ioncodes** [comment]
@vaahtokarkki It didn't work for me too on the last key, so I had to make my own tool. jodeldecompile probably doesn't work with the new jodel versions.

**Comment by vaahtokarkki** [comment]
@ioncodes Oh okay that explains! Would you mind pushing the updated key or some information how to obtain key? I have a project using this api in Helsinki's Jodel and would be nice to keep it running, since as it gained a bit of it's own audience 😃

**Comment by ioncodes** [comment]
@vaahtokarkki Sorry, but no. Sadly, it has been abused multiple times and I came to an agreement with jodel that I will not publish any tokens anymore.

**Comment by vaahtokarkki** [comment]
@ioncodes Okay, I understand totally! Let's hope Jodel rolls out some day a public api for developers

**Comment by nborrmann** [comment]
Just committed the new key.
