### ISSUE TITLE
Rate-Limits j.get_post_details_v3() 300 per minute

### ISSUE THREAD

**Issue by gitarre94** [nborrmann/jodel_api#62]
## Issue
j.get_post_details_v3()
maximum Requests are 300 per minute.
After that you get "Too Many Request" as reponse

...

## Environment

If you're reporting a bug, please attach the output of the following commands:

```
$ pip show jodel_api
$ pip -V
$ python -V
$ python -c "import jodel_api; print(jodel_api.JodelAccount.version); print(jodel_api.JodelAccount.secret)"
```

**Comment by nborrmann** [comment]
There are lots of rate-limits that frequently change. Theres not much we can do about it.
