### ISSUE TITLE
Get Comments for post_id

### ISSUE THREAD

**Issue by andrelanger** [nborrmann/jodel_api#66]
Hello everybody,

when I invoke j.get_post_details_v3(post_id, skip=0), it returns me a property "child_count" with the correct number of comments. However, the array in the property "children" is always empty.

So how do I retrieve the comment messages for a particular Jodel post_id?

André

**Comment by nborrmann** [comment]
You need to use skip=None

**Comment by andrelanger** [comment]
Thanks for the immediate reply.

> You need to use skip=None

I tested it, but the returned "children" array is still empty for j.get_post_details_v3(post_id, skip=None).
Does it work correctly for you?

**Comment by petrekova** [comment]
If you're looking for the comments, you will find them in the `replies` node. The children node always is empty, even when you're look up posts. Maybe it's a placeholder for future features.

So to retrieve an array of all comments of a post, your code could something like this:
```python
# initialize jodel_api beforehand
# Let's also assume that we have somehow retrieved a post_id with some comments

x = j.get_post_details_v3(post_id)
# comments are saved in array
comments = x[1]["replies"]
# take a look by prettyprinting them in the console (or a file if you want)
print json.dumps(comments,indent=4,sort_keys=True)
```

**Comment by andrelanger** [comment]
Thanks  for your comment, petrekova.

I only evaluated x[1]["details"] and was not aware of the other key "replies" so far.
That helped me a lot.

**Comment by petrekova** [comment]
Glad I could help @andrelanger
