### ISSUE TITLE
j.create_post() not working

### ISSUE THREAD

**Issue by stackola** [nborrmann/jodel_api#8]
After creating an account and updating the location, the call to j.create_post does not work, and just returns (478,478)

Any idea why this could be?

**Comment by nborrmann** [comment]
The account needs to be verified by solving a captcha challenge. I implemented this in the latest commit b079b58bad7eb57d9c0ea2933f113d302dab3aa1.

**Comment by stackola** [comment]
Yes, I found that out after looking at OJOC @ bitbucket
Thanks for the fast fix
