### ISSUE TITLE
does not work anymore

### ISSUE THREAD

**Issue by guitar9** [nborrmann/jodel_api#81]
Have the correct key but get error 477 Signed Request expected.

**Comment by ioncodes** [comment]
I'm still using this library for a few things but with my own keys, it should work.

**Comment by guitar9** [comment]
still with version 5.10.3? I cant create a new Account. I have the correct key. Get error 477.
Can you check, you have the same as me? I blacked out a piece in the middle because it is not wanted to publish the secret key.

![bildschirmfoto_2018-11-07_16-38-35](https://user-images.githubusercontent.com/25721108/48141856-015e2700-e2ac-11e8-970e-ed54502f9355.png)

**Comment by guitar9** [comment]
has somebody a fix?

**Comment by guitar9** [comment]
this is the key i tried: MNoRTIEDWBhrikFNEkwSpKhizdGFwBjCjBtEhErP
version: 5.7.2

**Comment by jacopo-j** [comment]
I can confirm everything works fine with the correct keys (issue should be closed). @guitar9 you must use keys from the latest version available.

**Comment by guitar9** [comment]
ok thank you. Jodel 5.7.2 is the latest version.... @jacopo-j can you check, if you have the same key? 
I used it for a few months but now it does not work anymore. Does not know what i am doing wrong

**Comment by ioncodes** [comment]
@guitar9 The latest version is 5.11.1 ...

**Comment by guitar9** [comment]
ok had a problem with my python files. Now it works...
