### ISSUE TITLE
FirebaseUID is not valid

### ISSUE THREAD

**Issue by Cylop** [nborrmann/jodel_api#86]
## Issue
I build a basic application that just creates an account and reads some popular jodels but I am facing the issue that the response for "GET" actions exits with the following exception:

`Exception: (401, {'error': 'Firebase UID not valid', 'metadata': None})` 

You can easily reproduce the error with the following code: 

```
import jodel_api


def create_jodel_account():
    lat, lng, city = 48.148434, 11.567867, "Munich"
    return jodel_api.JodelAccount(lat=lat, lng=lng, city=city)

def run_program():
    print("Account is getting created..")
    jodel_account = create_jodel_account()
    print("Acount was created")
    print("Account Data:")
    print(jodel_account.get_account_data())
    print(jodel_account.get_posts_popular(limit=10))


if __name__ == '__main__':
    run_program()
```
...

## Environment
I set up the environment a couple of seconds ago. It's fresh with only "jodel_api" installed.

If you're reporting a bug, please attach the output of the following commands:

I executed the following commands and you can see the output I got.

```
$ pip show jodel_api

(venv) MacBook-Pro:jodel-test dev$ pip show jodel_api
Name: jodel-api
Version: 1.2.11
Summary: Unoffical Python Interface to the Jodel API
Home-page: https://github.com/nborrmann/jodel_api
Author: Nils Borrmann
Author-email: n.borrmann@googlemail.com
License: MIT
Location: /Users/dev/PycharmProjects/jodel-test/venv/lib/python3.8/site-packages
Requires: protobuf, varint, mock, future, requests
Required-by: 
(venv) dev

$ pip -V

pip 21.1.2 

$ python -V

Python 3.8.5

$ python -c "import jodel_api; print(jodel_api.JodelAccount.version); print(jodel_api.JodelAccount.secret)"

4.79.1
b'HtJoqSysGFQXgFqYZRgwbpcFVAzLFSioVKTCwMcL'
```

**Comment by SydoxX** [comment]
I think this project is no longer actively maintained, thus the Firebase was probably removed. There have been some backend changes to the jodel API as well.

**Comment by Cylop** [comment]
Thank you, I'll investigate a bit and see what I can find
